### ISSUE TITLE
Session expire on deploy/restart

### ISSUE THREAD

**Issue by jakuub** [vacuumlabs/fine-tracker#100]
This is quite irritating for me - I want to use fine-tracker all the time, but each time new version is published, I need to log in again. I am happy, that releases are often, but it is quite disturbing and dissuasive from using fine-tracker

**Comment by jakuub** [comment]
I add it to 1.0, but it is not necessary.

**Comment by jakuub** [comment]
I changed this to a bug because if someone doesn't know this is not working, it looks like a bug - if someone submits worklogs, no error occurs, only loading never ends.

**Comment by jakuub** [comment]
After #126

**Comment by mikx98** [comment]
Resolved with SSO

**Comment by jakuub** [comment]
I don't think so. SSO resolves easier login, but does not resolve this. At least I think. 
Correct me if i'm wrong.

**Comment by jakuub** [comment]
This was duplicated in #270 , as this is original issue, I will close the duplicate. This was the description there:
> SSO resolved one pain, that I always needed to wait for Jira and Tempo. But the problem with lost session will be still there.
> 
> Let's figure out somehow, how to eliminate this also.
> Maybe by "relogin" on saving, "background relogin", or I don't know how. But my point is to be able to be logged in almost permanently without any need to relogin more often than to my google account.

**Comment by mikx98** [comment]
@jakuub true, let's do this asap then :+1:
